
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import { Toaster } from "sonner";   
import MyProvider from "./myProvider/MyProvider";
import CartProvider from '../context/cart.context'
import Footer from "./_components/Footer/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MyProvider>
        <CartProvider>
        <Navbar />
        <Toaster position="top-center" richColors />
        {children}
        <Footer></Footer>
        </CartProvider>
        </MyProvider>
      </body>
    </html>
  );
}
